# Generated by Django 5.1.4 on 2025-02-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Zoom", "Zoom"),
                            ("Meet", "Google Meet"),
                            ("Teams", "Microsoft Teams"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("event_link", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="upcoming",
                        max_length=50,
                    ),
                ),
                ("meeting_start_time", models.TimeField()),
                ("meeting_end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
