# Generated by Django 5.1.4 on 2024-12-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'user_type': 'B2B_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'B2B_USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='institutionuser',
            index=models.Index(fields=['user', 'institution'], name='institution_user_id_d5048e_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionuser',
            index=models.Index(fields=['code'], name='institution_code_fce3a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionuser',
            unique_together={('user', 'institution')},
        ),
    ]
