# Generated by Django 5.1.4 on 2025-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='plan_type',
            field=models.CharField(choices=[('BASE', 'Base'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium')], default='BASE', max_length=20),
        ),
    ]
