# Generated by Django 5.1.4 on 2025-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_institution_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
