# Generated by Django 5.1.4 on 2025-02-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuracy', '0001_initial'),
        ('indexAndCommodity', '0005_alter_insight_prediction_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyOfIndexAndCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy', to='indexAndCommodity.trade')),
            ],
        ),
    ]
