# Generated by Django 5.1.4 on 2025-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accuracy", "0002_accuracyofindexandcommodity"),
    ]

    operations = [
        migrations.AddField(
            model_name="accuracy",
            name="target_hit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accuracy",
            name="total_days",
            field=models.IntegerField(
                blank=True, help_text="Total days taken for trade completion", null=True
            ),
        ),
    ]
