# Generated by Django 5.1.4 on 2025-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('strategy', models.CharField(choices=[('POSITIONAL', 'Positional'), ('INTRADAY', 'Intraday'), ('BTST', 'BTST')], max_length=20)),
                ('pdf_upload', models.FileField(blank=True, null=True, upload_to='stockreports/pdfs/')),
            ],
        ),
    ]
