# Generated by Django 5.1.4 on 2025-01-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexAndCommodity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='index_and_commodity',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tradehistory',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='IndexAndCommodity',
        ),
        migrations.DeleteModel(
            name='Insight',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
    ]
