# Generated by Django 5.1.4 on 2025-01-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexAndCommodity', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_free_call',
        ),
    ]
