# Generated by Django 5.1.4 on 2025-02-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexAndCommodity', '0005_alter_insight_prediction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='index_and_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='indexAndCommodity.indexandcommodity'),
        ),
    ]
