# Generated by Django 5.1.4 on 2025-01-18 09:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField(db_index=True, help_text='Unique identifier for the trading instrument', unique=True)),
                ('exchange', models.CharField(db_index=True, help_text='Stock exchange where the instrument is traded', max_length=10)),
                ('trading_symbol', models.CharField(db_index=True, help_text='Trading symbol used on the exchange', max_length=50)),
                ('script_name', models.CharField(help_text='Full name of the trading instrument', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date for F&O instruments', null=True)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=255)),
                ('instrument_type', models.CharField(choices=[('EQUITY', 'Equity'), ('FNO_FUT', 'F&O Future'), ('FNO_CE', 'Call Option'), ('FNO_PE', 'Put Option')], db_index=True, default='EQUITY', help_text='Type of trading instrument', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the instrument is currently tradeable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['trading_symbol', 'exchange', 'instrument_type'], name='trades_comp_trading_d51e24_idx')],
                'constraints': [models.UniqueConstraint(fields=('trading_symbol', 'exchange', 'instrument_type', 'expiry_date'), name='unique_trading_instrument')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('INTRADAY', 'Intraday'), ('POSITIONAL', 'Positional')], db_index=True, help_text='Type of trade (Intraday/Positional)', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the trade', max_length=20)),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium')], default='BASIC', help_text='Subscription plan type for this trade', max_length=15)),
                ('warzone', models.PositiveIntegerField(default=0, help_text='Risk level indicator for the trade (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_free_call', models.BooleanField(default=False, help_text='Indicates if this is a free trading signal')),
                ('image', models.ImageField(blank=True, help_text='Technical analysis chart or related image', null=True, upload_to='trade_images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the trade was completed or cancelled', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trades.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_image', models.ImageField(help_text='Technical analysis prediction chart', upload_to='trade_insights/predictions/')),
                ('actual_image', models.ImageField(blank=True, help_text='Actual outcome chart', null=True, upload_to='trade_insights/actuals/')),
                ('prediction_description', models.TextField(help_text='Detailed description of the predicted outcome')),
                ('actual_description', models.TextField(blank=True, help_text='Description of the actual outcome', null=True)),
                ('accuracy_score', models.FloatField(blank=True, help_text='Percentage accuracy of the prediction', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='trades.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bull_scenario', models.TextField(help_text='Analysis of potential bullish outcomes')),
                ('bear_scenario', models.TextField(help_text='Analysis of potential bearish outcomes')),
                ('status', models.CharField(choices=[('BEARISH', 'Bearish'), ('BULLISH', 'Bullish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', help_text='Current market sentiment', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the analysis was completed', null=True)),
                ('analysis_result', models.JSONField(blank=True, default=dict, help_text='Structured analysis result with sections and paragraphs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trades.trade')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, help_text='Entry price point', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target', models.DecimalField(decimal_places=2, help_text='Target price for the trade', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sl', models.DecimalField(decimal_places=2, help_text='Stop loss price point', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Stop Loss')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trades.trade')),
            ],
            options={
                'verbose_name_plural': 'Trade histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status', 'trade_type', 'plan_type'], name='trades_trad_status_4994e9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['created_at', 'user'], name='trades_trad_created_a14db5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradehistory',
            index=models.Index(fields=['trade', 'timestamp'], name='trades_trad_trade_i_d8eaa7_idx'),
        ),
    ]
