# Generated by Django 5.1.4 on 2025-01-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_remove_analysis_analysis_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name_plural': 'Trade histories'},
        ),
    ]
