# Generated by Django 5.1.4 on 2025-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_insight_actual_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, help_text='Technical analysis chart or related image', null=True, upload_to='', verbose_name='image'),
        ),
    ]
