# Generated by Django 5.1.4 on 2025-01-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_trade_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='actual_image',
            field=models.ImageField(blank=True, help_text='Actual outcome chart', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='prediction_image',
            field=models.ImageField(help_text='Technical analysis prediction chart', upload_to='', verbose_name='image'),
        ),
    ]
