# Generated by Django 5.1.4 on 2025-01-20 21:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_insight_actual_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='actual_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Actual outcome chart', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='prediction_image',
            field=cloudinary.models.CloudinaryField(help_text='Technical analysis prediction chart', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Technical analysis chart or related image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
