# Generated by Django 5.1.4 on 2025-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_alter_insight_actual_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='warzone',
            field=models.PositiveIntegerField(default=0, help_text='Risk level indicator for the trade (0-100)'),
        ),
    ]
