# Generated by Django 5.1.4 on 2025-01-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_alter_trade_warzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='bear_scenario',
            field=models.TextField(blank=True, help_text='Analysis of potential bearish outcomes', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='bull_scenario',
            field=models.TextField(blank=True, help_text='Analysis of potential bullish outcomes', null=True),
        ),
    ]
