# Generated by Django 5.1.4 on 2025-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_alter_company_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='warzone_history',
            field=models.JSONField(blank=True, default=list, help_text='History of warzone changes', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='warzone',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Risk level indicator for the trade', max_digits=10),
        ),
    ]
