# Generated by Django 5.1.4 on 2025-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_alter_trade_warzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='warzone',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Risk level indicator for the trade', max_digits=10),
        ),
    ]
