# Generated by Django 5.1.4 on 2025-01-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_alter_trade_warzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='instrument_type',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('FNO_FUT', 'F&O Future'), ('FNO_CE', 'Call Option'), ('FNO_PE', 'Put Option')], db_index=True, default='EQUITY', help_text='Type of trading instrument', max_length=20),
        ),
    ]
