# Generated by Django 5.1.4 on 2025-01-09 09:21

import apps.subscriptions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('B2B', 'Business'), ('B2C', 'Individual')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.subscriptions.models.validate_positive_price])),
                ('duration_days', models.PositiveIntegerField(default=30, validators=[apps.subscriptions.models.validate_positive_duration])),
                ('intended_users', models.CharField(max_length=255)),
                ('index_coverage', models.JSONField(default=dict)),
                ('stock_coverage', models.PositiveIntegerField()),
                ('commodity_analysis', models.TextField(blank=True)),
                ('client_interaction', models.CharField(max_length=255)),
                ('webinars', models.CharField(max_length=255)),
                ('portfolio_management', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['plan_type', 'price'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['is_visible', 'plan_type', 'price'], name='subscriptio_is_visi_a867de_idx'), models.Index(fields=['code'], name='subscriptio_code_34057e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.subscriptions.models.validate_positive_price])),
                ('payment_type', models.CharField(choices=[('OFFLINE', 'Offline Payment'), ('RAZORPAY', 'Razorpay Payment')], default='RAZORPAY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference number for offline payments', max_length=200, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_type'], name='subscriptio_status_bc751a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_19fd13_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_order_id'], name='subscriptio_razorpa_dd08d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_payment_id'], name='subscriptio_razorpa_b7b82e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='subscriptio_is_acti_395b46_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_24ff08_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_end_date_after_start_date'),
        ),
    ]
