# Generated by Django 5.1.4 on 2025-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('BASE', 'Base'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium')], max_length=30, unique=True),
        ),
    ]
