# Generated by Django 5.1.4 on 2025-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium'), ('FREE_TRIAL', 'Free Trial')], max_length=30),
        ),
    ]
