# Generated by Django 5.1.4 on 2025-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loginattempt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
