# Generated by Django 5.1.4 on 2025-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_trade_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_active',
        ),
        migrations.AddField(
            model_name='notification',
            name='detailed_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRADE', 'Trade Update'), ('ANALYSIS', 'Analysis Update'), ('PRICE', 'Price Update'), ('RISK', 'Risk Update'), ('INSIGHT', 'Trade Insight')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
