# Generated by Django 5.1.4 on 2025-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_redirectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='trade_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='trade_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
