# Generated by Django 5.1.4 on 2025-02-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_is_redirectable_notification_trade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_redirectable',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='trade_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='trade_status',
        ),
    ]
